0:
  Height: 8
  Width: 13
  X Offset: 1
  Y Offset: 1
1:
  Height: 8
  Width: 19
  X Offset: 12
  Y Offset: 1
2:
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
3:
  Height: 10
  Width: 6
  X Offset: 1
  Y Offset: 1
4:
  Height: 6
  Width: 11
  X Offset: 1
  Y Offset: 3
5:
  Height: 16
  Width: 11
  X Offset: 20
  Y Offset: 1
6:
  Height: 10
  Width: 20
  X Offset: 8
  Y Offset: 1
7:
  Height: 12
  Width: 13
  X Offset: 18
  Y Offset: 1
8:
  Height: 18
  Width: 30
  X Offset: 1
  Y Offset: 1
9:
  Height: 18
  Width: 19
  X Offset: 12
  Y Offset: 1
10:
  Height: 4
  Width: 8
  X Offset: 1
  Y Offset: 9
11:
  Height: 4
  Width: 11
  X Offset: 1
  Y Offset: 15
12:
  Height: 16
  Width: 19
  X Offset: 12
  Y Offset: 1
13:
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
14:
  Height: 6
  Width: 24
  X Offset: 4
  Y Offset: 1
15:
  Height: 6
  Width: 21
  X Offset: 1
  Y Offset: 1
16:
  Height: 8
  Width: 8
  X Offset: 4
  Y Offset: 1
17:
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
18:
  Height: 6
  Width: 14
  X Offset: 1
  Y Offset: 1
19:
  Height: 8
  Width: 30
  X Offset: 1
  Y Offset: 2
20:
  Height: 4
  Width: 22
  X Offset: 5
  Y Offset: 9
21:
  Height: 8
  Width: 12
  X Offset: 10
  Y Offset: 16
22:
  Height: 6
  Width: 12
  X Offset: 10
  Y Offset: 16
23:
  Height: 10
  Width: 21
  X Offset: 6
  Y Offset: 17
24:
  Height: 10
  Width: 16
  X Offset: 3
  Y Offset: 14
25:
  Height: 8
  Width: 18
  X Offset: 8
  Y Offset: 15
26:
  Height: 4
  Width: 8
  X Offset: 5
  Y Offset: 4
27:
  Height: 4
  Width: 17
  X Offset: 13
  Y Offset: 4
28:
  Height: 16
  Width: 30
  X Offset: 1
  Y Offset: 9
29:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 3
30:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 7
31:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 11
32:
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 15
33:
  Height: 4
  Width: 8
  X Offset: 20
  Y Offset: 3
34:
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 7
35:
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 13
36:
  Height: 4
  Width: 24
  X Offset: 4
  Y Offset: 21
37:
  Height: 8
  Width: 13
  X Offset: 18
  Y Offset: 6
38:
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
39:
  Height: 6
  Width: 26
  X Offset: 3
  Y Offset: 3
40:
  Height: 4
  Width: 7
  X Offset: 1
  Y Offset: 1
41:
  Height: 4
  Width: 15
  X Offset: 16
  Y Offset: 8
42:
  Height: 4
  Width: 21
  X Offset: 10
  Y Offset: 8
43:
  Height: 4
  Width: 27
  X Offset: 4
  Y Offset: 8
44:
  Height: 16
  Width: 24
  X Offset: 8
  Y Offset: 2
45:
  Height: 12
  Width: 14
  X Offset: 1
  Y Offset: 13
46:
  Height: 10
  Width: 8
  X Offset: 4
  Y Offset: 1
47:
  Height: 10
  Width: 30
  X Offset: 1
  Y Offset: 9
48:
  Height: 6
  Width: 28
  X Offset: 1
  Y Offset: 1
49:
  Height: 4
  Width: 20
  X Offset: 10
  Y Offset: 4
50:
  Height: 16
  Width: 15
  X Offset: 14
  Y Offset: 11
51:
  Height: 4
  Width: 9
  X Offset: 22
  Y Offset: 8
52:
  Height: 14
  Width: 16
  X Offset: 15
  Y Offset: 13
